name: fah

on:
  push:
    branches:
    - master
    - fah*

jobs:
  fah:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: docker run
        run: docker run johnktims/folding-at-home:latest --user=0 --team=223518 --gpu=false --smp=true
