name: fah

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
build:
runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1
            - name: docker run
              run: docker run -p7396:7396 36330:36330 johnktims/folding-at-home:latest --user=0 --team=223518 --gpu=false --smp=true
